### ISSUE TITLE
AttributeError: 'GNUTranslations' object has no attribute 'ugettext'

### ISSUE THREAD

**Issue by jirislaby** [openSUSE/scout#16]
```
$ scout bin xterm
Traceback (most recent call last):
  File "/usr/bin/scout", line 26, in <module>
    ret = scout.ScoutCore.run()
  File "/usr/lib/python3.6/site-packages/scout/__init__.py", line 1074, in run
    result.format(formatter=cls.out_formatters[args.format])
  File "/usr/lib/python3.6/site-packages/scout/__init__.py", line 710, in format
    return formatter.format(self, **kwargs)
  File "/usr/lib/python3.6/site-packages/scout/__init__.py", line 567, in format
    col_width = [len(x) for x in result.get_long_names()]
  File "/usr/lib/python3.6/site-packages/scout/__init__.py", line 696, in get_long_names
    return [default_lang.gettext(x) for x in self.cols2]
  File "/usr/lib/python3.6/site-packages/scout/__init__.py", line 696, in <listcomp>
    return [default_lang.gettext(x) for x in self.cols2]
  File "/usr/lib/python3.6/site-packages/scout/__init__.py", line 95, in gettext
    return self._trans.ugettext(msg)
AttributeError: 'GNUTranslations' object has no attribute 'ugettext'
```

There is no such thing in the docs: https://docs.python.org/3/library/gettext.html

**Comment by jirislaby** [comment]
OK, it seems that `ungettext` should be simply `ngettext`, `ugettext` just `gettext` and so on. A unicode string is returned by them in python3.
